# 运行项目
project_name: 统一管理平台

# 环境信息
host: https://192.168.148.174:31000

#全局登录接口
logincase: login_01

# 数据库相关配置
mysql_db:
  host: 192.168.148.174
  user: root
  password: ws-123456
  port: 3306

# 用例路径
casedata_path: bms/data
